### ISSUE TITLE
Two jobs are not found  "HR Manager" and "Junior Java Developer" from site peviitor.ro

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#10]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

Steps to reproduce

Open the company recruitee page: https://anahr.ro/domenii/joburi-pe-domenii/page/2/
Be careful to open the second jobs page too.
Open peviitor URL
Put the name "anahr" in the search field
Press the button "Caută"
Scroll until the end of displayed jobs
Pay attention that jobs  "HR Manager" and "Junior Java Developer" are not displayed

Expected results

  "HR Manager" and "Junior Java Developer" to be displayed on peviitor.ro after searching all the jobs from "anahr"

Actual results

There are no jobs with title  "HR Manager" and "Junior Java Developer" displayed on peviitor.ro after applying filter for searching the company "anahr"

![Screenshot 1](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/140fa727-e534-4c73-8068-c7ff566873a7)

**Comment by RaresCode** [comment]
Fixed
