### ISSUE TITLE
Autonet -  The message " Satu, Iulia, Timișoara, Târgu, Gheorghe ,is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#105]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Autonet  " Company
3. Click run Scrapers.
4. Check the job locations.

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website.

ACTUAL RESULTS:
The message " Satu, Iulia, Timișoara, Târgu, Gheorghe ,is not a city in Romania" is displayed instead of the job locations

ATTACHMENTS: 

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/e5476943-a6e5-4dc3-b32c-e4f968659d60)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Geo843** [comment]
Re-tested, Job locations are the same in Scrapers-UI as on the company website.
