### ISSUE TITLE
Atp-group - The message " Romania, Cluj, Oradea, Baia Mare is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#106]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " Atp-group" Company
3. Open "Run Scrapers" button
4. Check the job locations.

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website.

ACTUAL RESULTS:
 The message " Romania, Cluj, Oradea, Baia Mare is not a city in Romania" is displayed instead of the job locations

ATTACHMENTS: 

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/17828d5a-57f1-4ab8-9179-ceada24ae015)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Geo843** [comment]
Re-tested, Job locations are the same in Scrapers-UI as on the company website.
