### ISSUE TITLE
Anahr - NOT matches Jobs number on the peviitor.ro with https://anahr.ro/

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#109]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2. Search for the "Anahr" Company.
3. Click on the "Careers" button.
4. Open https://anahr.ro/en/areas/jobs-by-domains/
5. Click on the " See Jobs" button.
6. Open peviitor.ro

EXPECTED RESULTS:
The Jobs number on the peviitor.ro match with https://anahr.ro/

ACTUAL RESULTS:
NOT matches Jobs number on the peviitor.ro with https://anahr.ro/

ATTACHMENTS:

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/4d9915bc-1a82-4ea4-bfda-7df41ef4167b)

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/1364783b-06d6-4ead-9c4a-7c7364cc45e9)

**Comment by RaresCode** [comment]
Those are job categories, a job can be in multiple categories for instance Administrative / Logistics, output, accountancy, can you retest and check if there is really a bug regarding the number of jobs?

**Comment by Geo843** [comment]
Re-tested, The Jobs number on the peviitor.ro match with https://anahr.ro/
