### ISSUE TITLE
Aeroportoradea - Missing Company Logo

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#110]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for the company "Aeroportoradea "
3. Check the logo.

EXPECTED RESULTS:
The " Aeroportoradea  Company" logo is there and is functional.

ACTUAL RESULTS:
Error LOGO on the scrapers.peviitor.ro 

ATTACHMENTS: 

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/4865b231-479b-4cfe-8201-4d3471c5052d)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by Geo843** [comment]
Re-tested , The " Aeroportoradea Company" logo is there and is functional.
