### ISSUE TITLE
Ppromania - The message " Ilfov- Prahova is not a city in Romania" is displayed instead of the job locations 

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#111]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Ppromania  " Company
3. Open "Careers" button
4. Open " See jobs" button 
5. Check the job locations.

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website.

ACTUAL RESULTS:
The message " Ilfov- Prahova  is not a city in Romania" is displayed instead of the job locations.

ATTACHMENTS: 

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/34174a26-ff36-4c37-9af2-c54f51a68c66)

**Comment by RaresCode** [comment]
Fixed can you retest? Please ignore where it's mentioned "all is not a city in Romania" as this will work in the future update!

**Comment by Geo843** [comment]
Re-tested, Job locations are the same in Scrapers-UI as on the company website.
