### ISSUE TITLE
IPSO  - The message " Romania, TOATE JUDEȚELE ȚĂRII, Piatra Neamț, Bacău, Roman, Iași, Divizia Moldova, Târgu Mureș, is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by MarinaCosmina** [peviitor-ro/JobsScrapers#112]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1.Open the URL in the browser
2.Search for "IPSO" Company
3.Open "Run Scrapers" button
4.Check the job locations.

EXPECTED RESULTS:
Job locations should be the same on Scrapers-UI as on the company website.

ACTUAL RESULTS:
The message " Romania, TOATE JUDEȚELE ȚĂRII, Piatra Neamț, Bacău, Roman,
 Iași, Divizia Moldova, Târgu Mureș, is not a city in Romania" is displayed instead of the job locations

ATTACHMENTS:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/33ceaf8f-d1e7-432a-8012-9e5f4fc186d9)

**Comment by RaresCode** [comment]
Fixed can you retest? Please ignore where it's mentioned "all is not a city in Romania" as this will work in the future update!

**Comment by MarinaCosmina** [comment]
retested, all good
