### ISSUE TITLE
Bioclinica – On Bioclinica's website are 33 jobs available, on Scraper-UI the  jobs number is 0, on peviitor.ro are displayed 0 jobs.

### ISSUE THREAD

**Issue by MarinaCosmina** [peviitor-ro/JobsScrapers#113]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1.Open the URL in the browser
2.Search for "Bioclinica" Company
3.Open "Run Scrapers" button
4. Check “Jobs” number
5. Click "See jobs"
6. Open https://bioclinica.ro/compania/cariere
7. Check available jobs

EXPECTED RESULTS:
1. On Scraper-UI should appear the same number of jobs (33 jobs)
 listed in the career area on "Bioclinica" website.
2. On peviitor.ro should appear the 33 jobs  listed on "Bioclinica" website.

ACTUAL RESULTS:
1. On Scrapers-UI appears 0 jobs.
2. On peviitor.ro are 0 jobs listed for ‘Bioblinica’.

ATTACHMENTS:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/73ab1734-a690-4dc6-aa05-69014b1178f9)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/1676136e-b9a9-4125-bdd0-6b1fc21b805d)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/ba5e62a6-c58d-443b-8221-efe320e6df82)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/02aa78bc-405e-41a1-b913-ce906cd2d31d)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/288d0cd1-11dc-4b77-a1d6-a62338b29753)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by MarinaCosmina** [comment]
Re-tested, appears all 33 jobs.
