### ISSUE TITLE
Affidearomania - The message " Complex Cosmopolis  is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#117]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Affidearomania"  Company
3. Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:

The message "Complex Cosmopolis  is not a city in Romania" is displayed instead of the job locations.

ATTACHMENTS: 

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/9affd757-0cfb-460e-b34b-66b9863bab6f)

**Comment by RaresCode** [comment]
Fixed Can you retest?

**Comment by Geo843** [comment]
Re-tested, Job locations are the same in Scrapers-UI as on the company website
