### ISSUE TITLE
Sephora -  Assertion Error - Right contains one more item

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#118]
ENVIRONMENT: production
URL: https://peviitor-ro.github.io/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. See the ALLURE REPORT 
3. Click on the  "Categories"
4. Click on the "Product defects"
5. Check "Sephora" Jobs 

EXPECTED RESULTS:
The Left   side asserts match with The right side  asserts.

ACTUAL RESULTS:
 Assertion Error -Right contains one more item:
" At index 2 diff: 'DIRECTOR ADJUNCT MAGAZIN - TARGU MURES' != 'Beauty Adviser Part Time (6h/zi) - Promenada, Bucuresti' "

ATTACHMENTS: 

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/c163d213-9d68-444e-a586-8332e3eec62d)

**Comment by RaresCode** [comment]
Fixed can you retest?
