### ISSUE TITLE
Sandra - Assertion Error - Right contains one more item

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#119]
ENVIRONMENT: production
URL: https://peviitor-ro.github.io/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. See the ALLURE REPORT
3. Click on the "Categories"
4. Click on the "Product defects"
5. Check "Sandra " Jobs

EXPECTED RESULTS:
The Left side asserts match with The right side asserts.

ACTUAL RESULTS:
Assertion Error  - Right contains one more item:
At index 2 diff: 
'Tehnician auto' != 'Senior Manager PGP Production, Technology and Innovation - Region Europe East (m/f/d)' 

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/6795dc0e-431e-44ec-b0b7-bcb3677b06b8)

**Comment by RaresCode** [comment]
Fixed, can you retest?

**Comment by Geo843** [comment]
Re-tested,
