### ISSUE TITLE
Velpitar- The message "București, Cluj is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#121]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Velpitar" Company
3. Open "Run Scrapers" button
4. Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:
The message "București, Cluj is not a city in Romania" is displayed instead of the job locations.

ATTACHMENTS:
![velpitar](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/706d66e0-a1ed-44ba-83ab-7dc833984985)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Aniod01** [comment]
Re-tested, Job locations are the same in Scrapers-UI as on the company website
