### ISSUE TITLE
Saladbox - The message "Cluj is not a city in Romania" is displayed instead of the job locations.

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#123]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Saladbox" Company
3. Open "Run Scrapers" button
4. Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:
The message "Cluj is not a city in Romania" is displayed instead of the job locations.

ATTACHMENTS:
![saladbox](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/3536f3db-ba77-4ebb-8c8b-8a4a9a6011d7)

**Comment by RaresCode** [comment]
Can you retest?

**Comment by Aniod01** [comment]
Re-tested, job locations are the same in Scrapers-UI as on the company website
