### ISSUE TITLE
NOKIA - Careers site link does not work

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#125]
ENVIRONMENT: production
URL: https://peviitor.ro
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
 1. Open the [url](https://scrapers.peviitor.ro/src/nokia/index.html)
 2. Hover over the logo and click on Nokia Careers.

EXPECTED RESULTS:
  The careers section on the Nokia official website is open in browser.

ACTUAL RESULTS:
  An "invalid request" message is displayed on the opened page.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/e3f0d7d0-fdb7-4324-bb89-c53bad53cb6e)

**Comment by SimonaNemtanu** [comment]
Closed #125 as completed

**Comment by Aniod01** [comment]
An "invalid request" message is displayed when open the careers link on the Nokia official website: https://careers.nokia.com/jobs/search/40601155

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by SimonaNemtanu** [comment]
Same "invalid request" message 

![image](https://github.com/user-attachments/assets/d29d3b9c-76e0-4efd-8eff-b42e310d0098)
