### ISSUE TITLE
NOKIA - The job link is not a valid one and the displayed job opening does not exist anymore 

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#126]
ENVIRONMENT: production
URL: https://peviitor.ro
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
 1. Open the [url](https://scrapers.peviitor.ro/src/nokia/index.html)
 2. Click on "run scraper"
 3. Click on "vezi postul" from the Senior Solution Architect - Service Management job.

EXPECTED RESULTS:
  The Senior Solution Architect - Service Management job posting is displayed on the company's official website.

ACTUAL RESULTS:
  The careers section has moved, due to some changes in the recruitment system. See below:
  Also, it seems that on the new careers section the only job in Romania is a Product Component Engineer position.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/a5547dcb-e91e-4971-9e52-c4d1c2fa6971)

![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/09465e71-fe62-482d-a431-4773d060abef)

![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/f772e019-e587-4526-9d9a-432328511e17)

**Comment by Aniod01** [comment]
Nokia company does not exist on peviitor.ro
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/d2ff9769-9017-4591-9c47-d1e5c56d7c11)

**Comment by RaresCode** [comment]
Nokia will appear only when at least a job would be validated from the validator, please validate a job from the validator and try again.

**Comment by Aniod01** [comment]
After retesting, this company appear on peviitor.ro.
