### ISSUE TITLE
In the search box of the site "peviitor.ro" company "Hella" appears twice

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#13]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

- Steps to reproduce

1. Open peviitor.ro
2. Put the name "hella" in the search field
3. Press the button "Caută"

- Expected results
"Hella" should appear once on "peviitor.ro" site.

- Actual results
"Hella" appear twice on "peviitor.ro" site.

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/e4eb762d-ba54-4597-85b6-431d5b2d0ff5)

**Comment by RaresCode** [comment]
Fixed!
