### ISSUE TITLE
REGINAMARIA - API Error when scarper run

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#130]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Reginamaria" Company
3. Click on the "Run Scraper" button

Expected results:
All jobs should be displayed.

Actual results:
Scraper isn't loading, API error status.

Attachments:
![reginamaria](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/f667a2a6-7413-4daf-acbf-4eb325b78693)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Aniod01** [comment]
Re-Tested,  Scraper is loading
![reginamariaAPI](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/5ccc861f-8443-466f-9f05-28d77e163acf)
