### ISSUE TITLE
SONRISATECHNOLOGIES- position not available in Romania

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#131]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1.Open the URL in the browser.
2. Search for "sonrisatechnologies" Company
3. Click on "Run Scraper" button
4. Click on the  "sonrisatechnologies" careers button.
5. Check the job locations.

Expected results
Job locations should be the same on Scrapers-UI as on the company website.

Actual results
Job is displaying location in Romania, however on the careers page location is in Budapest- fully remote and on-site

Attachments:
![somrisaScrapers](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/a696f53f-3012-4907-8bc0-d3f3b872129c)
![sonrisa](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/b967970c-d460-426a-b50f-b54b2bb2afd2)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Aniod01** [comment]
After re-testing, API error status is displayed.
![apierrorSonrisa](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/d345f542-1a31-4c70-9734-c53f9b9f1048)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Aniod01** [comment]
Retested ✅
