### ISSUE TITLE
PPROMANIA - Wrong job type for "Manager Vanzari" position

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#133]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "ppromania" Company
3. Click on "Run Scraper" button
4. Check the jobs type

EXPECTED RESULTS:
Job types are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:
For "Manager Vanzari" position the job type doesn't correspond on the official website careers 
Attachments:
![ppromania](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/f10be002-efdf-4ca7-88ee-9d55ac84714c)
![ppRo](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/8d436cc3-bdf0-4d35-822c-84510a755b2a)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Aniod01** [comment]
Re-tested, the job type position "Manager Vanzari" correspond as on the official website careers
