### ISSUE TITLE
VELPITAR - The message "Cluj is not a city in Romania" is displayed, instead of job location

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#134]
ENVIRONMENT: production
URL: https://peviitor.ro
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
 1. Open the [url](https://scrapers.peviitor.ro/src/velpitar/index.html).
 2. Click on "run scraper".
 3. Scroll to "Electrician întreținere și reparații - București, Cluj" job.

EXPECTED RESULTS:
  The locations Bucuresti and Cluj are correctly displayed in the location section.

ACTUAL RESULTS:
  Bucuresti is displayed, but the message "Cluj is not a city in Romania" is displayed instead of Cluj.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/b16d4680-4049-4e51-a95f-e4912240fb6b)

**Comment by RaresCode** [comment]
Fixed can you retest?
