### ISSUE TITLE
PAGO- The type of job is not the same as on the official company page 

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#135]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Pago" Company
3. Click on "Run Scraper" button
4. Check the job type

EXPECTED RESULTS:
Job type are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:
The type of job is not the same as on the official company page 

Attachments:
![pago](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/8c0e89c1-df51-46ac-9324-28f4ad8a775a)
![PAGGO](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/49295cc5-ef33-4ab3-a1e5-bce0385cfe94)

**Comment by RaresCode** [comment]
Fixed can you retest?
