### ISSUE TITLE
CargoTrack - One job missing from scrapers.peviitor.ro

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#136]
ENVIRONMENT: production
URL: https://peviitor.ro
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
 1. Open the [url](https://scrapers.peviitor.ro/src/cargotrack/index.html) .
 2. Click on "run scraper".
 3. See that there are three jobs displayed.
 4. Open the [url](https://cargotrack.ro/cariere/).
 5. Scroll down to the careers.
 6. See that there are four available jobs.
 
EXPECTED RESULTS:
  The number of jobs from scrapers.peviitor.ro matches the number of available jobs from the company's official website.

ACTUAL RESULTS:
  The number of jobs from scrapers.peviitor.ro (3) does not match the number of available jobs from the company's official website (4).

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/f01469d8-6510-41ee-a08e-229961ae5407)

![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/16b69d12-e386-4b82-816d-464a3d392218)

![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/48cbc6d4-99e1-4d3b-9646-06acc64f9056)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Sarra113** [comment]
After retesting, the job that was missing - "customer support specialist" - is now displayed, but the extra job opportunity "vreau sa lucrez la CargoTrack" is now missing:

![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/3befadb6-8da5-4bf8-aeed-33a7fc755c06)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/153ab2af-35dd-4be1-b20a-b44cadbc4bd9)

**Comment by RaresCode** [comment]
That's a generic job application, we don't track those as they are used elsewhere.

**Comment by Sarra113** [comment]
Got it, thank you
