### ISSUE TITLE
Britishcouncil - The message " Cluj is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#137]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " Britishcouncil " Company
3. Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:
 The message " Cluj is not a city in Romania" is displayed instead of the job locations

ATTACHMENTS:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/73fe3657-e81b-4f2b-853c-1194e7757612)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Geo843** [comment]
Re-tested, Job locations are the same in Scrapers-UI as on the company website
