### ISSUE TITLE
NOODLEPACK - The message "Cluj Napoca is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#138]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Noodlepack" Company
3. Open "Run Scraper" button
4. Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:
The message "Cluj Napoca is not a city in Romania" is displayed instead of the job locations

ATTACHMENTS:
![noodlepack](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/bd7325d6-dc62-46a7-a392-1366be8d90f1)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Aniod01** [comment]
Re- tested, job locations are the same in Scrapers-UI as on the company website
