### ISSUE TITLE
SOFTEXCO -The message "Cluj Napoca is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#141]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Softexco" Company
3. Click on "Run Scraper" button
4. Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:
The message "Cluj Napoca is not a city in Romania" is displayed instead of the job locations

ATTACHMENTS:
![softesco](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/2f530b37-9f3f-4648-8f7f-59ba45ab3657)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Aniod01** [comment]
Re-Tested
Job locations are the same in Scrapers-UI as on the company website
