### ISSUE TITLE
BASWARE - None of the job types displayed match the job types from the company's website

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#142]
ENVIRONMENT: production
URL: https://peviitor.ro
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
 1. Open the [url](https://scrapers.peviitor.ro/src/basware/index.html)
 2. Click on "run scraper"
 3. See the displayed job types: "on-site"
 4. Click on "vezi postul" for each job displayed
 5. See the job type from the official company website: "hybrid"
 
EXPECTED RESULTS:
  The job types from scrapers.peviitor.ro match the job types from the company's website.

ACTUAL RESULTS:
  The job types from scrapers.peviitor.ro don't  match the job types from the company's website.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/6e46c65f-a2ad-4e67-9b1c-c69e0c05d3d1)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/25584adf-9ed6-4e9d-ab38-70b90e4ab48b)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/7941c471-e1d6-46b7-b0b9-87d5cf39e718)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/e5f9bb97-9385-4a36-b5c2-e336b95e60d8)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/39bf68bc-f78f-4221-9963-3ef10fec5529)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/4d79e145-49c4-4c3c-9d76-738f9d7e9278)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/13d3e4fd-7a76-43be-8b3e-04c97ce0d3e3)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/29b8173e-3613-40bf-bc81-771bc6456798)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/a14c54bc-6c02-4211-a553-4a5120b40fe1)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/7e8c942c-f8f9-4dea-8c8a-d6c22f4c861a)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/c247870b-a8a0-41fb-83b5-64e6df5ca154)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/516918fb-1782-448a-b82f-277da768b7e1)

**Comment by RaresCode** [comment]
fixed can you retest?
