### ISSUE TITLE
Kinetic - The message "Cluj is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#144]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "kinetic" Company
3. Click on "Run Scraper" button
4. Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:
The message "Cluj is not a city in Romania" is displayed instead of the job locations

ATTACHMENTS:
![kinetic](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/5a918cc5-5180-4102-a934-b53115e2402b)
![kinetic-cariere](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/efb7aee2-bb78-4e9c-979f-1911ebc85712)

**Comment by Aniod01** [comment]
Retested, the message "Cluj is not a city in Romania" is fixed . 
Location should be only Bucuresti.

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by Aniod01** [comment]
Retested ✅
