### ISSUE TITLE
Jobshop - The message "Iasi is not a city in Romania" or "Remote is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#145]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "jobshop" Company
3. Click on "Run Scraper" button
4. Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:
The message "Iasi is not a city in Romania" or "Remote is not a city in Romania" is displayed instead of the job locations

ATTACHMENTS:
![jobshop](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/7f9d7850-fae6-4175-bd6a-231f6a83517c)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Aniod01** [comment]
Re-tested, job locations are the same in Scrapers-UI as on the company website.
