### ISSUE TITLE
Jobshop- Job types do not match the company's official website 

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#146]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2. Search for "jobshop" Company
3. Open "Run Scrapers" button
4. Check the job types

EXPECTED RESULTS:
The job types should match the information provided by the official website for "Devops Engineer - Automation" and "Devops Engineer – Env Suppor" position.

ACTUAL RESULTS:
Discrepancies are observed in job types.

ATTACHMENTS:
![jobshoptype](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/b92a29d9-6b5a-4b71-a9d2-0eb58a028bb5)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Aniod01** [comment]
Re-tested, the job types correspond with the information provided by the official website.
