### ISSUE TITLE
Iuliuscompany- The message "Cluj is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#147]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "iuliuscompany" Company
3. Click on "Run Scraper" button
4. Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:
The message "Cluj is not a city in Romania" is displayed instead of the job locations

ATTACHMENTS:
![iuliuscompany](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/6d96c7ba-9929-440f-9803-b48753852fba)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Aniod01** [comment]
Retested, job locations are the same in Scrapers-UI as on the company website.
