### ISSUE TITLE
HTECGroup - Job location not correctly displayed. The job is not in Romania

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#148]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/htecgroup/index.html
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
 1. Open the [url](https://scrapers.peviitor.ro/src/htecgroup/index.html)
 2. Click on "run scraper"
 3. Click on "vezi postul" from the first job displayed - "Kragujevac Internship"
 4. Compare the job location displayed on scrapers.peviitor.ro with the one from the company's website.

EXPECTED RESULTS:
  The  job location displayed on scrapers.peviitor.ro matches the one from the company's website and is in Romania.

ACTUAL RESULTS:
  The job location displayed on scrapers.peviitor.ro does not match the one from the company's website. The actual location is in Serbia.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/a32f49bd-101d-4176-aa28-05fb92c7660d)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/c5609706-50d8-47cf-aab3-1688869ccc73)

**Comment by RaresCode** [comment]
Fixed can you retest?
