### ISSUE TITLE
Interbrandsorbico -No jobs are displayed on Scraper-UI and on peviitor.ro

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#149]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1. Open the URL in the browser
2. Search for "interbrandsorbico" Company
3. Open "Run Scrapers" button
4. Check “Jobs” number

EXPECTED RESULTS:
On Scraper-UI should appear the same number of jobs (63 jobs)
listed in the career area on "interbrandsorbico" website.
On peviitor.ro should appear the 63 jobs listed on "interbrandsorbico" website.

ACTUAL RESULTS:
No jobs are displayed.

ATTACHMENTS:
![inter1](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/e5c98edc-77e8-47e1-a69a-aded356ad852)
![inter2](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/d3afc11a-8c76-4cdb-abcb-37a39c70690e)
![inter](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/94c5a413-e281-43d2-bfa0-cae44dc94815)

**Comment by RaresCode** [comment]
Fixed, can you retest?

**Comment by Aniod01** [comment]
Retested, jobs are displayed.
