### ISSUE TITLE
The link from button "Vezi postul" on site "https://peviitor.ro/" displayed the form for application.

### ISSUE THREAD

**Issue by FloBut** [peviitor-ro/JobsScrapers#15]
Enviroment

url: https://peviitor.ro/
browser: Chrome
device: Computer
OS: windows

Steps to reproduce

1. Open the company careers page: https://www.conexdist.ro/ro/cariere/
2. Pay attention to no of jobs displayed
3. Open peviitor - url
4. Put the name "conexdist" in the search field
5. Press the button "cauta"
6. Scroll until the end of displayed jobs
7. Click on button "Vezi postul" for each job displayed

Expected results:
Job description to be displayed on "peviitor.ro" after press the button "Vezi postul" from site "https://www.conexdist.ro/ro/cariere/"

Actual results:
The link from button "Vezi postul" on site "https://peviitor.ro/" displayed the form for application.

**Comment by RaresCode** [comment]
Fixed!
