### ISSUE TITLE
Intelligentbee -  Job types do not match the company's official website

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#151]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2. Search for "Intelligentbee" Company
3. Click on the "Run Scrapers" button
4. Check the job types
6. Click the "Vezi Postul" button for each job
7. Observe job description on the company's official job listing webpage

EXPECTED RESULTS:
The job types should match the information provided by the official website..

ACTUAL RESULTS:
Discrepancies are observed in job types.

ATTACHMENTS:
![inteligentbee1](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/e2603c24-779c-4e1b-8e32-f48a9a0161d3)
![inteligentbee2](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/8f7b5a4c-b0bb-418e-82d5-20d49c558b1d)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Aniod01** [comment]
Retested.
