### ISSUE TITLE
Affidea-Romania Missing jobs on "peviitor"

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/JobsScrapers#152]
ENVIRONMENT: production
URL: https://peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
 1. Open the url https://scrapers.peviitor.ro/src/affidearomania/index.html
 2.Check job number

EXPECTED RESULTS:
The jobs number is displayed correctly according to https://affidearomania.recruitee.com/

ACTUAL RESULTS:
  The jobs number is "0"
 FAILED ..\tests\Test_API_Suite\test_affidearomania.py::test_affidearomania_title_api - AssertionError: Scraper is not grabbing any job titles

Attachments:
![Screenshot_37](https://github.com/peviitor-ro/JobsScrapers/assets/124587607/f15b6866-5cfc-462e-92ae-22d0daebb3c4)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by LarisaM16** [comment]
is ok now
