### ISSUE TITLE
Ensemblesoftware - Job types do not match the company's official website

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#154]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2. Search for "Ensemblesoftware" Company
3. Open "Run Scrapers" button
4. Check the job types

EXPECTED RESULTS:
The job types should match the information provided by the official website. 

ACTUAL RESULTS:
Discrepancies are observed in job types, remote work option is not displayed.

ATTACHMENTS:
![ensemblesoftware](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/a7bef168-ac50-415a-ad66-0d00341cf925)
![ensembleofficial](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/2585b04f-3d03-49d9-a7d8-6c82b21bb407)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Aniod01** [comment]
Retested, now is displayed only remote job types but current opportunities is in Baia Mare, Brasov, Cluj or Remote. The job types should be On-site/remote.

**Comment by Aniod01** [comment]
Retested, no more jobs are available at this moment.
