### ISSUE TITLE
Bioclinica - The message "Târgu Mureș is not a city in Romania" is displayed instead of job location

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#155]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/bioclinica/index.html
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
 1. Open the[ url](https://scrapers.peviitor.ro/src/bioclinica/index.html)
 2. Click on "run scraper"
 3. Scroll to "Manager zonal"
 4. Click on "Vezi postul"
 5. Compare the job location from the company's website with the job location displayed on scrapers.peviitor.ro.

EXPECTED RESULTS:
  The job locations match - Targu Mures.

ACTUAL RESULTS:
  The message "Târgu Mureș is not a city in Romania" is displayed instead of the job location on scrapers.peviitor.ro.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/db8cfa1a-6aed-41f4-bbfd-2d9a63381b23)

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by Sarra113** [comment]
Verified - fixed
