### ISSUE TITLE
Interbrandsorbico -The message "Cluj Napoca is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#157]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser
Search for "interbrandsorbico" Company
Click on "Run Scraper" button
Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:
The message "Cluj Napoca is not a city in Romania" is displayed instead of the job locations

ATTACHMENTS:
![interbrands](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/0d4239df-19d8-42ee-bf0a-4f637e14c496)

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by Aniod01** [comment]
Retested ✅
