### ISSUE TITLE
DUAL IT - The number of jobs on scraper-UI does not match the number of jobs from the company's official website

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#159]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/dualit/index.html
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
 1. Open the [url](https://scrapers.peviitor.ro/src/dualit/index.html)
 2. Click on "run scraper"
 3. Open the [url](https://dualitsoft.com/careers/)
 4. Compare the number of jobs displayed on scrapers.peviitor to the number of jobs from Dual IT website.

EXPECTED RESULTS:
  The number of jobs on scraper-UI matches the number of jobs from the company's official website.

ACTUAL RESULTS:
  The number of jobs on scraper-UI does not match the number of jobs from the company's official website.
  
Note: There are at least three jobs for Romania, as they are located in Cluj-Napoca. The other ones appear as remote.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/67d46ce2-eb81-49ef-b993-356e6cbf7296)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/fc03fbf0-2a72-4799-81a1-1d5b97cba212)

**Comment by Aniod01** [comment]
Retested ✅
