### ISSUE TITLE
Missing job "Mecanic auto service turisme Oradea" from site peviitor.ro

### ISSUE THREAD

**Issue by FloBut** [peviitor-ro/JobsScrapers#16]
Enviroment

URL: https://peviitor.ro/
browser: Chrome
device: Computer
OS: windows

Steps to reproduce

1. Open the company careers page: https://atp-group.ro/cariere/
2. Pay attention to no of jobs displayed
3. Open peviitor URL
4. Put the name "atpgroup" in the search field
5. Press the button "cauta"
6. Scroll until the end of displayed jobs
7. Pay attention that job "Mecanic auto service turisme Oradea" is not displayed
8. Expected results

"Mecanic auto service turisme Oradea " to be displayed on peviitor.ro after searching all the jobs from "atpgroup"

Actual results

There are no job with titles "Mecanic auto service turisme Oradea" displayed on peviitor.ro after applying filter for searching the company "atpgroup"

**Comment by RaresCode** [comment]
Fixed!
