### ISSUE TITLE
Creatopy- Job types and locations does not match with the official website 

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#160]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2. Search for "creatopy" Company
3. Open "Run Scrapers" button
4. Navigate to and click the "Careers" button.
5. Observe all job types and locations.

EXPECTED RESULTS:
The job types and locations should match the information provided by the official website.

ACTUAL RESULTS:
Discrepancies are observed in job types, remote work option is not displayed and job locations does not match the information provided by company's website.

Attachments:
![creatcopy](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/80ab58d8-274a-4aa8-a425-d4404baeeddb)
![creatcopy1](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/8ff53111-36d0-4046-91e8-790fa7f0b443)

**Comment by RaresCode** [comment]
Can you retest?

**Comment by Aniod01** [comment]
Retested, job types is fixed but job location is not fixed.
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/06c82753-edb4-41e0-9107-25e4ec2e95ea)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/16d49715-8ac8-466a-93eb-c3e830381e4c)

**Comment by Aniod01** [comment]
Retested ✅
