### ISSUE TITLE
CONSULTMED - Incorrect county - In the job presentation from peviitor.ro the city is Iași and the county Brașov

### ISSUE THREAD

**Issue by MarinaCosmina** [peviitor-ro/JobsScrapers#161]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
1.Open the URL in the browser
2.Search for "Consultmed" Company
3.Open "Run Scrapers" button
4. Click on "See jobs".

EXPECTED RESULTS:
In the job presentation from peviitor.ro, for the city Iași the county should be also Iași

ACTUAL RESULTS:
In the job presentation from peviitor.ro the city is Iași and the county Brașov.

ATTACHMENTS:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/d25307c3-8c05-49d6-8848-109f9529c460)

**Comment by RaresCode** [comment]
Fixed can you retest
