### ISSUE TITLE
Conexdist -The message "Cluj is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#162]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "conexdist" Company
3. Click on "Run Scraper" button

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:
The message "Cluj is not a city in Romania" is displayed instead of the job locations

ATTACHMENTS:
![conexdist](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/f0f86e35-edf2-4965-9b83-24efe2a311f3)

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by Aniod01** [comment]
I retested,  but now location is "Cluj-Napoca" instead "Cluj"

**Comment by RaresCode** [comment]
Yes, as the job city is Cluj Napoca and the county is Cluj

**Comment by Aniod01** [comment]
I see that on the official website the job location is Cluj and on scraper-ui is Cluj-Napoca
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/35800e6e-ebc9-4a16-ad2a-45699da8783d)

**Comment by RaresCode** [comment]
Cluj-Napoca is the capital city of Cluj County, which is located in the Transylvania region of Romania.
It's intentionally modified to display cluj napoca and not cluj as that is a county.
It's an error on the website rather than the scraper.

**Comment by Aniod01** [comment]
All is ok, thanks.
