### ISSUE TITLE
KAIZEN GAMING - The number of job form scraper-UI does not match the number of jobs available on the company's official website

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#163]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/kaizengaming/
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Open the [url](https://scrapers.peviitor.ro/src/kaizengaming/)
Click on "run scraper"
Open the [url](https://careers.kaizengaming.com/apply)
From the location box drop down, select Bucharest.
Compare the number of jobs displayed on scrapers.peviitor to the number of jobs from Kaizen Gaming website.

EXPECTED RESULTS:
The number of jobs on scraper-UI matches the number of jobs from the company's official website.

ACTUAL RESULTS:
The number of jobs on scraper-UI does not match the number of jobs from the company's official website.
Scraper returns 0 jobs, but there is one job available for Bucharest.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/2feb8ce3-d572-43ac-a622-259c7bc72a7b)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/1500dd46-e327-4048-b97f-d7c45bcb8fbc)

**Comment by Aniod01** [comment]
Retested ✅
