### ISSUE TITLE
Expert Mind - The locations from scraper-UI do not match the locations from the company's website

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#168]
ENVIRONMENT: production
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Open the [url](https://scrapers.peviitor.ro/src/expertmind/index.html)
Click on "run scraper"
Click on "vezi postul" for each of the five jobs displayed.
Compare the job locations displayed on scrapers.peviitor to the locations for each job from the official website.

EXPECTED RESULTS:
The locations displayed on scrapers-UI match the locations from the company's website.

ACTUAL RESULTS:
The locations displayed on scrapers-UI do not match the locations from the company's website:
The scraper returns "Iasi, Bucuresti" for every job, not only for the first one.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/a3ca827d-d50f-4784-87a3-025050352217)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/d4f0460f-f691-4179-b9bf-1ec9d445b7a6)

**Comment by RaresCode** [comment]
Fixed can you retest?
