### ISSUE TITLE
Logo is not displayed from site peviitor.ro 

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#17]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

- Steps to reproduce

1.Open peviitor URL
2.Put the name "Nolimits" in the search field
3.Press the button "Caută"
4.You will saw that the logo not appeared 

- Expected results

Logo to appear on the "peviitor.ro" site
- Actual results

Logo not appear on the "peviitor.ro" site

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/7699c9d3-bd84-45fb-a8df-acf132b48944)

**Comment by RaresCode** [comment]
Fixed!
