### ISSUE TITLE
Cargus - The locations displayed on scraper-UI do not match the locations from the company's website

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#172]
ENVIRONMENT: production
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Open the [url](https://scrapers.peviitor.ro/src/cargus/)
Click on "run scraper"
Click on "vezi postul" for each of the five jobs displayed.
Compare the job locations displayed on scrapers.peviitor to the locations for each job from the official website.

EXPECTED RESULTS:
The locations displayed on scrapers-UI match the locations from the company's website.

ACTUAL RESULTS:
The locations displayed on scrapers-UI do not match the locations from the company's website:
The scraper returns "Bucuresti, Timisoara, Cluj-Napoca, Brasov, Iasi" for the first job "Cargus caută curier/șofer/livratori cu autoutilitare proprii", whereas on the company's website this job this job is available all over the country.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/a4c3043d-869d-4e85-924d-04167507b864)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/f87565a1-b276-49ed-919e-a538b62ff31a)

https://github.com/peviitor-ro/JobsScrapers/assets/136991701/e5b12004-c03b-4d62-a0fc-dd12c8baee9a

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by Sarra113** [comment]
Restested

**Comment by Sarra113** [comment]
The previous problem is fixed but now the scraper returns the message "all is not a city in Romania" for the first job opening. 

![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/2acb96f0-0411-451e-9ae5-19b09e33c6cc)

**Comment by RaresCode** [comment]
that is intentional as it's a Național job
