### ISSUE TITLE
APAVITAL- The job locations displayed on "peviitor.ro" do not match the company's official website 

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#173]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Apavital" Company
3. Click on the "Run Scraper" button
4. Click on the "See Jobs" button 
5. Click on the "Careers" button.
6. Observe the job locations

EXPECTED RESULTS:
The job locations dispalyed on [peviitor.ro]( https://peviitor.ro/rezultate?company=apavital&country=Rom%C3%A2nia&page=1) should match the information provided by the  [Apavital]( https://www.apavital.ro/cariere ) official website.

ACTUAL RESULTS:
The job locations dispalyed on [peviitor.ro]( https://peviitor.ro/rezultate?company=apavital&country=Rom%C3%A2nia&page=1)  do not match the information provided by the  [Apavital]( https://www.apavital.ro/cariere ) official website.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/46aff111-aab8-41e9-b333-703a3665af96)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/4790c27b-5a52-4f59-b46a-2cff64d4cc5a)

**Comment by RaresCode** [comment]
Fixed can you retest ?

**Comment by Aniod01** [comment]
Retested ✅
