### ISSUE TITLE
AUTOSIENA- The job locations displayed on "scrapers.peviitor.ro" and on "peviitor.ro" do not match the company's official website

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#174]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Autosiena" Company
3. Click on the "Run Scraper" button
4. Click on the "See Jobs" button
5. Click on the "Careers" button.
6. Observe the job locations

EXPECTED RESULTS:
The job locations dispalyed on [scrapers.peviitor.ro](https://scrapers.peviitor.ro/src/autosiena/index.html)  and on  [peviitor.ro](https://peviitor.ro/rezultate?company=autosiena&country=Rom%C3%A2nia&page=1) should match the information provided by the [Autosiena](https://autosiena.ro/cariera/#1) official website.

ACTUAL RESULTS:
The job locations dispalyed on [scrapers.peviitor.ro](https://scrapers.peviitor.ro/src/autosiena/index.html)  and on  [peviitor.ro](https://peviitor.ro/rezultate?company=autosiena&country=Rom%C3%A2nia&page=1) do not match the information provided by the [Autosiena](https://autosiena.ro/cariera/#1) official website.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/eef2fd52-bb49-47c9-9a80-081ba68898ac)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/14510401-8d18-4006-81f5-3b431c87b5aa)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/74b09ce7-7167-46f3-a678-53e42928f1fc)

**Comment by RaresCode** [comment]
fixed can you retest

**Comment by Aniod01** [comment]
Retested- The job location dispalyed on scrapers-ui/peviitor.ro do not match the information provided by the Autosiena official website. Is displayed "Satu Mare" instead "Oradea".

**Comment by RaresCode** [comment]
fixed can you retest again?

**Comment by Aniod01** [comment]
Re-tested, the job location is not written with capital letters

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Aniod01** [comment]
Retested ✅
