### ISSUE TITLE
ARCADIA MEDICAL - the job locations from Scrapers-UI 'Iasi' does not match the job location displayed on peviitor.ro 'Iasi, Brasov'

### ISSUE THREAD

**Issue by MarinaCosmina** [peviitor-ro/JobsScrapers#176]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser
Search for "Arcadia" Company
Click on the "Run Scraper" button
Check job locations from Scrapers-UI
Click on the "See Jobs" button
Check job locations from peviitor.ro

EXPECTED RESULTS:
The job locations displayed on Scraper-UI should match the job location from peviitor.ro 

ACTUAL RESULTS:
The job locations displayed on Scraper-UI 'Iasi'  does not match the job locations displayed on peviitor.ro 'Iasi, Brasov'

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/9b0eee9a-15e1-4049-92b5-ad5dc405d8ff)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/610ade84-66be-40b5-8ec3-a8d16d756fdc)

**Comment by RaresCode** [comment]
fixed can you retest

**Comment by MarinaCosmina** [comment]
Retested - the location appears correct
