### ISSUE TITLE
Intelligentbee - The job location does not match the information on the company's website for one of the job listings 

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#178]
ENVIRONMENT: production
URL: https://peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
 1. Open the url
 2. Type "Intelligentbee" in search field
 3. Press on search button
 4. Click on "Run Scraper"
 5. Navigate to and click the "Careers" button. 

EXPECTED RESULTS:
The job location displayed on scrapers-UI for  "QA Tester - 6 months contract, hybrid, Bucuresti" role match information on the company's website

ACTUAL RESULTS:
The job location displayed on scrapers-UI for  "QA Tester - 6 months contract, hybrid, Bucuresti" role does not match information on the company's website

ATTACHMENTS:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/2fb8d072-9dc5-499a-a0b8-605529a7da67)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/3c3a3f68-9432-481a-ad51-0bc5d4c186c1)

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by Aniod01** [comment]
Retested ✅
