### ISSUE TITLE
AUTOCLASS - the job location from Scrapers-UI does not match the job location displayed on peviitor.ro 

### ISSUE THREAD

**Issue by MarinaCosmina** [peviitor-ro/JobsScrapers#179]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser
Search for "Autoclass" Company
Click on the "Run Scraper" button
Check job locations from Scrapers-UI
Click on the "See Jobs" button
Check job locations from peviitor.ro

EXPECTED RESULTS:
The job locations from on Scraper-UI should match the job location displayed on peviitor.ro

ACTUAL RESULTS:
The job locations from Scraper-UI "Satu Mare" does not match the job locations displayed on peviitor.ro. On peviitor.ro appears in addition location "Arad".

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/575a9293-88f8-4233-bc75-18d7c92c59df)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/cf9a74fa-7338-4d5b-8603-9bad0602840f)

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by MarinaCosmina** [comment]
Retested - the location appears correct
