### ISSUE TITLE
Missing jobs from site peviitor.ro, company  "Reinert"

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#18]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

- Steps to reproduce

1. Open the company recruitee page: https://reinert-romania.ro/ro/cariere/
2. Pay attention that are showed twelve jobs
3. Open peviitor URL
4. Put the name "Reinert" in the search field
5. Press the button "Caută"
6.  Pay attention that is displayed only a job

- Expected results

It should displayed on peviitor.ro site  all the jobs from "Reinert"

- Actual results

There is displayed only a job on peviitor.ro

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/745e7cba-a2e5-48df-9efb-f1b094e58ef7)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by IvanSorina** [comment]
Retest.
