### ISSUE TITLE
Intelligentbee - Incorrect County of the job listings on "peviitor.ro"

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#181]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
 1. Open the url
 2. Type "Intelligentbee" in search field
 3. Press on search button
 4. Click on "Run Scraper" button
 5. Click on "See jobs"
 6. Check the county of the jobs

EXPECTED RESULTS:
 In the job listings from "peviitor.ro", for the city "Iași" we expected to see the county "Iași"

ACTUAL RESULTS:
In the job listings from "peviitor.ro" we see the village "Iași" and the county "Brașov"

ATTACHMENTS:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/6fa3144b-b658-47d8-ac4e-1ea74d1ab8df)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/e80b2f80-3a3e-4b0d-8acb-047d2e9bf1b8)

**Comment by RaresCode** [comment]
fixed can you retest

**Comment by Aniod01** [comment]
Retested, the county is correct.
