### ISSUE TITLE
CALCROM - The job locations displayed for the results do not match the ones from scraper-UI and from the company's website

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#184]
ENVIRONMENT:

url: https://peviitor.ro/
browser: Chrome
device: laptop
OS: Windows
Version: 10

STEPS TO REPRODUCE:

Open [url](https://peviitor.ro/) in browser
Type "calcrom" in the serach bar.
Analyze the jobs' locations.

EXPECTED RESULTS:
The jobs' locations match the locations from [scrapers-UI ](https://scrapers.peviitor.ro/src/calcrom/index.html) and from the [company's website.](https://calcrom.ro/#careers)

ACTUAL RESULTS:
Each job has another location - Brasov, which is not displayed on scrapers-UI or on the company's website. The company is located only in Iasi.

Attachments:
![image](https://github.com/peviitor-ro/search-engine/assets/136991701/bd110ccc-1c03-4415-bdce-bbbe0a47638c)
![image](https://github.com/peviitor-ro/search-engine/assets/136991701/581d73f4-8386-47b4-8055-8d330accc379)
![image](https://github.com/peviitor-ro/search-engine/assets/136991701/2862c6c5-e00b-46e7-a419-5909e00fbc51)

**Comment by RaresCode** [comment]
fixed can you retest

**Comment by Sarra113** [comment]
Retested ✅
