### ISSUE TITLE
EXPRESSCREDIT - The locations displayed as results on the search engine do not match the locations from scraper-UI and from the company's website

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#186]
ENVIRONMENT:

url: https://peviitor.ro/
browser: Chrome
device: laptop
OS: Windows
Version: 10

STEPS TO REPRODUCE:

Open [url](https://peviitor.ro/) in browser.
Type "expresscredit" in the serach bar.
Analyze the jobs' locations.

EXPECTED RESULTS:
The jobs' locations match the locations from [scrapers-UI ](https://scrapers.peviitor.ro/src/expresscredit/index.html) and from the [company's website.](https://www.expresscredit.ro/despre-express-credit-amanet/cariere/#1)

ACTUAL RESULTS:
Each job has another location - Brasov, which is not displayed on scrapers-UI or on the company's website. The company is located only in Iasi.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/ec024cb1-b5f5-4f7e-a954-9e3d3c823290)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/b8383dc6-e3fe-4e66-89c5-14d8bbf6a441)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/dadd41d9-90f9-4029-8f9f-01ddcece2d43)

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by Sarra113** [comment]
Retested ✅
