### ISSUE TITLE
BRAS - The locations displayed as results on the search engine do not match the locations from scraper-UI and from the company's website

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#187]
ENVIRONMENT:

url: https://peviitor.ro/
browser: Chrome
device: laptop
OS: Windows
Version: 10

STEPS TO REPRODUCE:

Open [url](https://peviitor.ro/) in browser.
Type "bras" in the serach bar.
Analyze the jobs' locations.

EXPECTED RESULTS:
The jobs' locations match the locations from [scrapers-UI ](https://scrapers.peviitor.ro/src/bras/index.html) and from the [company's website.](https://bras.ro/cariere-bras/#!#1)

ACTUAL RESULTS:
Each job has another location - Brasov, which is not displayed on scrapers-UI or on the company's website. The company is located only in Iasi.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/e487a381-05ae-4ba4-84c5-e8763d2961ce)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/ca096fb3-1380-4fc3-a96b-8c13969f03db)

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by Sarra113** [comment]
Retested ✅
