### ISSUE TITLE
ELECTRA - The locations displayed as results on the search engine do not match the locations from scraper-UI and from the company's website

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#188]
ENVIRONMENT:

url: https://peviitor.ro/
browser: Chrome
device: laptop
OS: Windows
Version: 10

STEPS TO REPRODUCE:

Open [url](https://peviitor.ro/) in browser.
Type "electra" in the serach bar.
Analyze the jobs' locations.

EXPECTED RESULTS:

The jobs' locations match the locations from [scrapers-UI ](https://scrapers.peviitor.ro/src/electra/index.html) and from the [company's website.](https://www.electra.ro/ro/cariere/inginer-electronist-electra)

ACTUAL RESULTS:
Each job has another location - Brasov, which is not displayed on scrapers-UI or on the company's website. The company is located only in Iasi.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/aa08b8db-fe80-4be1-902a-740928bd0698)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/d5c73353-7ab7-4d28-8112-745a83389f6a)

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by Sarra113** [comment]
Retested ✅
