### ISSUE TITLE
BEENEAR - The locations displayed as results on the search engine do not match the locations from scraper-UI and from the company's website

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#189]
ENVIRONMENT:

url: https://peviitor.ro/
browser: Chrome
device: laptop
OS: Windows
Version: 10

STEPS TO REPRODUCE:

Open [url](https://peviitor.ro/) in browser.
Type "beenear" in the serach bar.
Analyze the jobs' locations.

EXPECTED RESULTS:

The jobs' locations match the locations from [scrapers-UI ](https://scrapers.peviitor.ro/src/beenear/) and from the [company's website.](https://beenear.com/career/)

ACTUAL RESULTS:

Each job has another location - Brasov, which is not displayed on scrapers-UI or on the company's website. The company is located only in Iasi.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/805c275c-e0a1-4341-af16-5655a3fb7b74)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/a561e1c1-623c-416f-b5b1-445c431cd21f)

**Comment by RaresCode** [comment]
fixed can you retest

**Comment by Sarra113** [comment]
Retested ✅
