### ISSUE TITLE
CARGUS - The locations displayed as results on the search engine do not match the locations from scraper-UI and from the company's website

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#190]
ENVIRONMENT:

url: https://peviitor.ro/
browser: Chrome
device: laptop
OS: Windows
Version: 10

STEPS TO REPRODUCE:

Open [url](https://peviitor.ro/) in browser.
Type "cargus" in the serach bar.
Analyze the jobs' locations.

EXPECTED RESULTS:
The jobs' locations match the locations from [scrapers-UI ](https://scrapers.peviitor.ro/src/cargus/) and from the [company's website.](https://www.cargus.ro/cariere/agent-telesales/)

ACTUAL RESULTS:
The Telesales executive job appears to be in Magurele, Bistrita-Nasaud, instead of in Magurele, Ilfov.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/18728199-b146-478c-b2de-db6b14442c35)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/b11ccc05-c8ea-44e1-9913-717e90623d0a)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/f646e867-69d6-43f7-bd21-7b59e805017c)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Sarra113** [comment]
Retested ✅
