### ISSUE TITLE
DUKTECH - The locations displayed as results on the search engine do not match the locations from scraper-UI and from the company's website

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/JobsScrapers#191]
ENVIRONMENT:

url: https://peviitor.ro/
browser: Chrome
device: laptop
OS: Windows
Version: 10

STEPS TO REPRODUCE:

Open [url](https://peviitor.ro/) in browser.
Type "duktech" in the serach bar.
Analyze the jobs' locations.

EXPECTED RESULTS:
The jobs' locations match the locations from [scrapers-UI ](https://scrapers.peviitor.ro/src/duktech/index.html) and from the [company's website.](https://www.duk-tech.com/career)

ACTUAL RESULTS:
Each job has another location - Brasov, which is not displayed on scrapers-UI or on the company's website. The company is located only in Iasi.

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/ea7745b8-9cdc-46e0-95a8-2288169a2b1a)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/e383db92-6c2c-460d-927c-6374e381dcf1)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/136991701/2f6ff3f8-b928-4df6-b553-8bd7e9d923d4)

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by Sarra113** [comment]
Retested ✅
