### ISSUE TITLE
PAGO -  The job location displayed on scraper-UI is "Bucharest" instead of "Bucuresti"

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#197]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "pago" Company
3. Click on "Run Scraper" button
4. Check the job locations

EXPECTED RESULTS:
The job locations displayed on scraper-UI should be "Bucuresti".

ACTUAL RESULTS:
The job location displayed on scraper-UI is "Bucharest" instead of "Bucuresti"

ATTACHMENTS:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/048470c1-248c-4799-b503-9757e08909ee)

**Comment by RaresCode** [comment]
This is not a bug, the end user will not see the scrapers-ui result only the result from the peviitor.ro "https://peviitor.ro/rezultate?company=pago&country=Rom%C3%A2nia&page=1".

**Comment by RaresCode** [comment]
fixed can you retest

**Comment by Aniod01** [comment]
Retested, all good.
