### ISSUE TITLE
Missing jobs from site peviitor.ro

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#20]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

- Steps to reproduce

1. Open the company recruitee page: https://www.rndautomatic.com/en/Career.html
2. Pay attention that are showed four jobs
3. Open peviitor URL
4. Put the name "rndautomatic" in the search field
5. Press the button "Caută"
6. Pay attention that is displayed only a job "Mechanical Design Engineer".

- Expected results

It should displayed on peviitor.ro site all the jobs from "rdnautomatic" site.

- Actual results

There is displayed only a job on peviitor.ro

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/60ea72ef-f7b2-4a4a-9f60-0a7b60f6035e)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by IvanSorina** [comment]
Retest.
