### ISSUE TITLE
Speedservicesatumare - Incorrect county in the job listings on "peviitor.ro"

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#200]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the url
2. Type "speedservicesatumare" in search field
3. Press on search button
4. Click on "Run Scraper" button
5. Click on "See jobs"
6. Check the county of the jobs
 

EXPECTED RESULTS:
In the job listings from "peviitor.ro", for the city "Satu Mare" we expected to see the county "Satu Mare"

ACTUAL RESULTS:
In the job listings from "peviitor.ro" we see the village "Satu Mare" and the county "Arad"

ATTACHMENTS:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/c0f437b9-354e-4d5f-ad2f-6ff5109187ae)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/f22e74a4-c058-4525-97fa-59bb6165a0cd)

**Comment by RaresCode** [comment]
fixed can you retest

**Comment by Aniod01** [comment]
Retested, now the jobs is not displayed on Scraper-UI and on peviitor.ro.
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/5c507469-797b-4141-ab97-ca6b74d0ae86)

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by Aniod01** [comment]
Retested ✅
