### ISSUE TITLE
RDNAUTOMATIC- Incorrect County for two job results on peviitor.ro

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#203]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the url
Type "rdnautomatic" in search field
Press on search button
Click on "Run Scraper" button
Click on "See jobs"
Check the county of the jobs

EXPECTED RESULTS:
In the job listings from "peviitor.ro" the county must be the same as on the company's website.

ACTUAL RESULTS:
In the job listings from "peviitor.ro" the county is not the same as on the company's website.
Instead of the city "Satu Mare" and the county "Satu Mare" is displayed the village "Satu Mare" and the county "Arad" .

ATTACHMENTS:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/a54bf05c-7672-43b0-bd53-cbed857e02f4)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/ceea8055-2a43-4001-8dbb-9ff67229faf6)

**Comment by RaresCode** [comment]
fixed can you retest

**Comment by Aniod01** [comment]
Retested.
