### ISSUE TITLE
ELLISIUM - Incorrect County in the job results from peviitor.ro

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#205]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the url
2. Type "ellisium" in search field
3. Press on search button
4. Click on "Run Scraper" button
5. Click on "See jobs"
6. Check the county of the jobs

EXPECTED RESULTS:
In the job listings from "peviitor.ro" the county must be the same as on the company's website.

ACTUAL RESULTS:
In the job listings from "peviitor.ro" the county is not the same as on the company's website.
Instead of the city "Iasi" and the county "Iasi" is displayed the village "Iași" and the county "Brașov" .

ATTACHMENTS:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/5d0bd875-eff2-49a1-9404-4a255bf90813)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/1164b7af-f685-4069-9bf2-d9a1dc850609)

**Comment by RaresCode** [comment]
fixed can you retest

**Comment by Aniod01** [comment]
Retested.
