### ISSUE TITLE
Bbcollection- API Staus Inactive

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#206]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "bbcollection" Company
3. Click on the "Run Scraper" button

Expected results:
The the company's database is updated.

Actual results:
API Status inactive

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/08d124cd-3e12-4ec3-b7b5-010becbaa074)

**Comment by RaresCode** [comment]
it seems to work can you retest?

**Comment by Aniod01** [comment]
Re-tested, the scraper run correctly.
