### ISSUE TITLE
VETRO - API Status "Inactive"

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#207]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "vetro" Company
3. Click on the "Run Scraper" button
4. Check the "Status" section

Expected results:
The scraper runs correctly and the message "Active" is displayed in the "Status" section

Actual results:
The "Inactive" message is displayed in the "Status" section

Attachments:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/3117c136-ec1e-4e58-b971-ad03e5aa0fad)

**Comment by RaresCode** [comment]
it seems to work can you retest?

**Comment by Aniod01** [comment]
Retested, the scraper run correctly.
