### ISSUE TITLE
EXPOMEDICS - API Status "Inactive"

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#209]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the url
2. Type "expomedics" in search field
3. Press on search button
4. Click on the "Run Scraper" button
5. Check the "Status" section

EXPECTED RESULTS:
The scraper runs correctly and the message "Active" is displayed in the "Status" section

ACTUAL RESULTS:
The "Inactive" message is displayed in the "Status" section

ATTACHMENTS:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/88ac0358-81aa-478a-a884-c70e715ae525)

**Comment by RaresCode** [comment]
it seems to work can you retest?

**Comment by Aniod01** [comment]
Retested, API status is "Active"
