### ISSUE TITLE
Missing "saladbox" company from peviitor.ro

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#21]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

- Steps to reproduce

1. Open peviitor URL
2. Put the name "saladbox" in the search field
3. Press the button "Caută"
4. Pay attention that is no displayed 

- Expected results

It should displayed on peviitor.ro the company  "saladbox" 

- Actual results

There is no displayed the company "saladbox"  on peviitor.ro

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/3078de9b-d3b8-4b08-8aff-a99aeabc5cf7)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by IvanSorina** [comment]
Retest.
