### ISSUE TITLE
Interbrandsorbico - API Status "Inactive"

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#210]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the url
Type "interbrandsorbico" in search field
Press on search button
Click on the "Run Scraper" button
Check the "Status" section

EXPECTED RESULTS:
The scraper runs correctly and the message "Active" is displayed in the "Status" section

ACTUAL RESULTS:
The "Inactive" message is displayed in the "Status" section

ATTACHMENTS:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/e2ada7dd-f33c-4791-b348-32d010249df6)

**Comment by RaresCode** [comment]
it seems to work now can you retest?
