### ISSUE TITLE
ZEELANDIA - API status inactive

### ISSUE THREAD

**Issue by MarinaCosmina** [peviitor-ro/JobsScrapers#212]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
Open theURL in the browser
Search for "Zeelandia" company
Press on search button
Click on  "Run Scraper" button
Check  "Status" section

EXPECTED RESULTS:
The scraper runs correctly and the message "Active" is displayed in the "Status" section

ACTUAL RESULTS:
The "Inactive" message is displayed in the "Status" section

ATTACHMENTS:
![image](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/69df8725-54bc-458f-a4f9-10373cb63cfd)

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by MarinaCosmina** [comment]
Retested - all good status 'Active'
