### ISSUE TITLE
ROMBAT -The "404" page not found is displayed for the "Inginer automatist" job

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#217]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the url
2. Type "rombat" in search field
3. Press on "Cauta" button
4. Click on "Vezi postul" button for the "Inginer automatist" job

EXPECTED RESULTS:
  The "Inginer automatist" job posting is displayed after clicking on the "Vezi postul" button

ACTUAL RESULTS:
  The "404" page not found is displayed after clicking on the "Vezi postul" button.

Attachments:

https://github.com/peviitor-ro/JobsScrapers/assets/63416053/ab9f25b0-f663-4db3-891d-b90605a3a84a

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by Aniod01** [comment]
Retested, the job is displayed.
