### ISSUE TITLE
InterbrandsOrbico - The message "•Bistrita is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#220]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "interbrandsorbico" Company
3. Click on "Run Scraper" button
4. Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:
The message "•Bistrita is not a city in Romania" is displayed instead of the job locations

Attachments:

![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/faf7f436-8c5a-4923-9b54-9ed4d07ff957)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/63416053/ded3c26b-b287-4646-ae44-67aa9cd3e5d0)

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by Aniod01** [comment]
Retested ✅
