### ISSUE TITLE
Missing CANOPY Company in Scraper UI

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/JobsScrapers#231]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open the URL https://scrapers.peviitor.ro/
Write "Canopy" in the search bar

EXPECTED RESULTS:
The company "Canopy" should be found and displayed in the search results when entered in the search bar.

ACTUAL RESULTS:
The company "Canopy" is not found or displayed in the search results.

**Comment by RaresCode** [comment]
company does not have any jobs currently, closing this.
