### ISSUE TITLE
Missing CONLAN Company in Scraper UI

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/JobsScrapers#232]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open the URL https://scrapers.peviitor.ro/
Write "Conlan" in the search bar

EXPECTED RESULTS:
The company "Conlan" should be found and displayed in the search results when entered in the search bar.

ACTUAL RESULTS:
The company "Conlan" is not found or displayed in the search results.

**Comment by RaresCode** [comment]
can you retest on validator?
