### ISSUE TITLE
PANIFCOM - Not found on https://admin.peviitor.ro/

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#238]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open URL in browser
  2. Type "panifcom" in the search bar.

EXPECTED RESULTS:
  The company is displayed.

ACTUAL RESULTS:
  The company is not found on https://admin.peviitor.ro/

Attachments:
![image](https://github.com/user-attachments/assets/7f51562a-b289-4be0-9fb3-81d3874d5372)

**Comment by RaresCode** [comment]
can you retest?

**Comment by Aniod01** [comment]
Retested ,the company is found on https://admin.peviitor.ro/
