### ISSUE TITLE
Missing "signaliduna" company from peviitor.ro

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#24]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

- Steps to reproduce

1. Open peviitor URL
2. Put the name "signaliduna" in the search field
3. Press the button "Caută"
4. Pay attention that is no displayed

- Expected results

It should displayed on peviitor.ro the company "signaliduna"

- Actual results

There is no displayed the company "signaliduna" on peviitor.ro

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/14904bf0-7b2e-4caa-9182-761176fda386)

**Comment by RaresCode** [comment]
It seems to be fixed by the previous ci run, can you retest??

**Comment by IvanSorina** [comment]
Retest.
