### ISSUE TITLE
QUBIZ- Link does not work

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/JobsScrapers#240]
ENVIRONMENT: production
URL: https://admin.peviitor.ro/
Browser: Chrome
Version: 120
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:
  
  1. Open URL in browser.
  2. Click on "Companii"
  3. Click on the "Cauta aici..." search bar.
  4. Write "Qubiz"
  5. Click on "Vizualizeaza joburi"
  6. Click on "Catre Job" for each job listings

EXPECTED RESULTS:
 The job description of the selected position opens

ACTUAL RESULTS:
 The link for all job listings does not work properly

Attachments:

https://github.com/user-attachments/assets/3012c757-84f7-4fb4-993f-b32c7acfd699

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Aniod01** [comment]
Re-tested, job link works fine.
