### ISSUE TITLE
Missing "softexco" company from peviitor.ro 

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#25]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

- Steps to reproduce

1. Open peviitor URL
2. Put the name "softexco" in the search field
3. Press the button "Caută"
4. Pay attention that is no displayed

- Expected results

It should displayed on peviitor.ro the company "softexco"

- Actual results

There is no displayed the company "softexco" on peviitor.ro

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/8c5c5bbd-79f0-4ee6-ab79-dba8f9f8548e)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by IvanSorina** [comment]
Retest.
