### ISSUE TITLE
Missing job "MECANIC AUTO" from site peviitor.ro 

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#27]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

- Steps to reproduce

1.Open the company recruitee page: https://speedservicesatumare.ro/cariere/
2.Pay attention that are two jobs displayed
3.Open peviitor URL
4.Put the name "speedservicesatumare" in the search field
5.Press the button "Caută"
6.Pay attention that job "MECANIC AUTO" is not displayed

- Expected results

  " MECANIC AUTO" to be displayed on peviitor.ro after searching all the jobs from "speedservicesatumare"

- Actual results

There are no job with titles   " MECANIC AUTO" displayed on peviitor.ro after applying filter for searching the company "speedservicesatumare

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/7d803c3e-a4e7-4490-8e7a-e7b69dbc8ae5)
"

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by IvanSorina** [comment]
Retest.
