### ISSUE TITLE
Missing "reinert" company from peviitor.ro site.

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#29]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

- Steps to reproduce

1. Open peviitor URL
2. Put the name "reinert" in the search field
3. Press the button "Caută"
4. Pay attention that is no displayed

- Expected results

It should displayed on peviitor.ro the company "reinert"

- Actual results

There is no displayed the company "reinert" on peviitor.ro

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/6d7c0aa6-4e44-46e9-b343-b30a37ee177c)

**Comment by RaresCode** [comment]
The current website career's section it's being worked on, I will need to delay the fix

**Comment by IvanSorina** [comment]
Retest

**Comment by IvanSorina** [comment]
Retest.
