### ISSUE TITLE
connectgroup  verified

### ISSUE THREAD

**Issue by FloBut** [peviitor-ro/JobsScrapers#3]
** Enviroment** 
- prod: https://peviitor.ro/
- browser: Microsoft Edge
- device: Computer
- os: windows

** Steps to reproduce**
- open link company in browser 
- click and copy all jobs to excel worksheet
- open link https://peviitor.ro/
- fill the name connectgroup 
- press button "cauta"
- checked if the no of jobs are the same 
- checked if the name of company is displayed under each job 
- checked if word the "Romania" is displayed under each jobs
- checked if the link of jobs works 
- checked if the logo is correct 

**Expected result**
- no of job to be same on platform "peviitor" and on site "https://www.connectgroup.com/en/vacancies/roemeni%C3%AB"
- word the "Romania" is displayed under each job
- link of jobs works
- the name of company is displayed under each job 
- logo to be correct displayed

**Actual result**
- no of job are the same on both sites
- the word  "Romania" is displayed under each job
- each link of jobs works 
- the name of company is displayed under each job 
- the link of jobs works

**Comment by RaresCode** [comment]
Fixed
