### ISSUE TITLE
Missing job "ȘEF BIROU SECURITATE AEROPORTUARĂ" from site peviitor.ro, company "aeroportoradea"

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#30]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

- Steps to reproduce

1.Open the company recruitee page: https://www.aeroportoradea.ro/ro/locuri-de-munca-vacante.html
2.Pay attention that are four jobs displayed
3.Open peviitor URL
4.Put the name "aeroportoradea" in the search field
5.Press the button "Caută"
6.Pay attention that job "ȘEF BIROU SECURITATE AEROPORTUARĂ" is not displayed

- Expected results

  "ȘEF BIROU SECURITATE AEROPORTUARĂ" to be displayed on peviitor.ro after searching all the jobs from "aeroportoradea" 

- Actual results

There are no job with titles "ȘEF BIROU SECURITATE AEROPORTUARĂ" displayed on peviitor.ro after applying filter for searching the company "aeroportoradea"

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/af8989ec-4d70-4c80-b709-2a414cf952ed)

**Comment by RaresCode** [comment]
Fixed

**Comment by IvanSorina** [comment]
Retest.
