### ISSUE TITLE
"Project Quotation Specialist" doesn't not found to "nielseniq" site

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#33]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

- Steps to reproduce

1.Open the company recruitee page: https://nielseniq.com/?s=&market=global&language=en&orderby=&order=&post_type=career_job&job_locations=romania&job_teams=&job_types=
2.Pay attention that are showed four jobs
3.Open peviitor URL
4.Put the name "nielseniq" in the search field
5.Press the button "Caută"
6.Pay attention that is displayed five jobs.
7. Press the button "Vezi postul" from job "Project Quotation Specialist"
8. You observe that this job is expired.

- Expected results

It should't displayed on peviitor.ro site the job "Project Quotation Specialist"  at "nielseniq" company.

- Actual results

It is displayed on peviitor.ro site the job "Project Quotation Specialist"  at "nielseniq" company.

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/1f9276b1-ab41-4fa9-b975-239344c20ae2)

**Comment by RaresCode** [comment]
Fixed

**Comment by IvanSorina** [comment]
Retest.
