### ISSUE TITLE
Missing job "Production Operator AOI" from site peviitor.ro, company "kimballelectronics"

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#34]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

- Steps to reproduce

1. Open the company recruitee page: https://kei.wd1.myworkdayjobs.com/en-US/GlobalKimballCareers?locations=fbecff70217d10da6c755135d69d6c29
2. Pay attention that are showed nine jobs
3. Open peviitor URL
4. Put the name "kimballelectronics" in the search field
5. Press the button "Caută"
6. Verify if this job "Production Operator AOI" appears.

- Expected results

It should displayed  the job "Production Operator AOI" at "peviitor.ro" site

- Actual results
It shouldn't displayed  the job "Production Operator AOI" at "peviitor.ro" site.

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/bc0ae459-62d5-43e6-9a73-b21ab125ddf8)

**Comment by RaresCode** [comment]
fixed

**Comment by IvanSorina** [comment]
Retest.
