### ISSUE TITLE
Missing job "Manager EDU TRUST" from site peviitor.ro, company "edutrust"

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#35]
URL: https://peviitor.ro/
browser: Chrome
device: Computer
OS: windows

- Steps to reproduce

1. Open the company recruitee page: https://www.edutrust.ro/cariera/
2. Pay attention that are showed two jobs
3. Open peviitor URL
4. Put the name "edutrust" in the search field
5. Press the button "Caută"
6. You observe that  job "Manager EDU TRUST" is missing.

- Expected results

It should displayed the job "Manager EDU TRUST"at "peviitor.ro" site.

- Actual results
It shouldn't displayed the job "Manager EDU TRUST"at "peviitor.ro" site.

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/f605a605-d05d-4b22-9fde-744b7bd1a38e)

**Comment by RaresCode** [comment]
Fixed, can you retest??

**Comment by IvanSorina** [comment]
Retest.
