### ISSUE TITLE
Missing job "Senior Software Developer (Embedded)" from site peviitor.ro, company "cscale"

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#36]
URL: https://peviitor.ro/
browser: Chrome
device: Computer
OS: windows

- Steps to reproduce

1. Open the company recruitee page: https://www.c-scale.ro/careers
2. Pay attention that are showed two jobs
3. Open peviitor URL
4. Put the name "cscale" in the search field
5. Press the button "Caută"
6. You observe that job "Senior Software Developer (Embedded)" is missing.

- Expected results

It should displayed the job "Senior Software Developer (Embedded)" at "peviitor.ro" site.

- Actual results

It shouldn't displayed the job "Senior Software Developer (Embedded)"at "peviitor.ro" site.

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/7540defd-fd3c-4dfe-95af-a228b22dc3a5)

**Comment by RaresCode** [comment]
Fixed, can you retest?
