### ISSUE TITLE
Missing "ramadaiasi" company from peviitor.ro site.

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#37]
URL: https://peviitor.ro/
browser: Chrome
device: Computer
OS: windows

- Steps to reproduce

1.Open peviitor URL
2.Put the name "ramadaiasi" in the search field
3.Press enter button
4. Pay attention that is no displayed

- Expected results

It should displayed on peviitor.ro the company "ramadaiasi"

- Actual results

There is no displayed the company "ramadaiasi" on peviitor.ro

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/ece45a14-3385-41c3-862c-a9072026c0e8)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by IvanSorina** [comment]
Retest.
