### ISSUE TITLE
Missing jobs from site peviitor.ro, company "allengra" 

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#38]
URL: https://peviitor.ro/
browser: Chrome
device: Computer
OS: windows

- Steps to reproduce

1. Open the company recruitee page: https://allengra.eu/career.php
2. Pay attention that are showed four jobs
3. Open peviitor URL
4. Put the name "allengra" in the search field
5. Press the enter button
6. Pay attention that is displayed only a job "RTL Design Engineer".

- Expected results

It should displayed on peviitor.ro site all the jobs from "allengra" site.

- Actual results

There is displayed only a job on peviitor.ro

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/e98caaea-a7f6-4382-838d-a4939795af12)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by IvanSorina** [comment]
Retest.
