### ISSUE TITLE
Missing jobs from site peviitor.ro, company "autoclass" 

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#39]
URL: https://peviitor.ro/
browser: Chrome
device: Computer
OS: windows

- Steps to reproduce

1. Open the company recruitee page: https://www.autoclass.ro/info/cariera.html
2. Pay attention that are showed seven jobs
3. Open peviitor URL
4. Put the name "autoclass" in the search field
5. Press the enter button
6. Pay attention that is displayed only a job "Mecanic auto".

- Expected results

It should displayed on peviitor.ro site all the jobs from "auto class" site.

- Actual results

There is displayed only a job on peviitor.ro

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/aa86b259-a206-4146-a845-f03c1a3ec6c7)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by IvanSorina** [comment]
Retest.
