### ISSUE TITLE
Missing job " Mecanic Auto" from site peviitor.ro, company "autosiena"

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#40]
URL: https://peviitor.ro/
browser: Chrome
device: Computer
OS: windows

- Steps to reproduce

1. Open the company recruitee page: https://autosiena.ro/cariera/
2. Pay attention that are showed two jobs
3. Open peviitor URL
4. Put the name "autosiena" in the search field
5. Press the enter button
6. You observe that job "Mecanic Auto" is missing.

- Expected results

It should displayed the job "Mecanic Auto" at "peviitor.ro" site, company "autosiena".

- Actual results

It shouldn't displayed the job "Mecanic Auto" at "peviitor.ro" site, company "autosiena".

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/612f5439-4e0e-4aae-b464-db5b0114c48e)

**Comment by RaresCode** [comment]
Fixed can you retest??

**Comment by IvanSorina** [comment]
Retest.
