### ISSUE TITLE
Missing jobs from site peviitor.ro, company "apavital"

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#41]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

- Steps to reproduce

1. Open the company recruitee page: https://www.apavital.ro/cariere
2. Pay attention that are two pages of jobs.
3. Open peviitor URL
4. Put the name "apavital" in the search field
5. Press the enter button
6. Pay attention that is displayed only jobs that are appeared to first page.

- Expected results

It should displayed on peviitor.ro site all the jobs from "apavital" site.

- Actual results

There is displayed only jobs that are appeared to first page.

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/c9ad6e41-065a-4917-ab2e-27d8482ae243)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by IvanSorina** [comment]
Retest.
