### ISSUE TITLE
Four jobs are not displayed on peviitor.ro from the company “BIT Software”

### ISSUE THREAD

**Issue by MarinaCosmina** [peviitor-ro/JobsScrapers#42]
URL: https://peviitor.ro/
browser: Chrome
device: Computer
OS: windows

Steps to reproduce
1. Open “BIT Software” career page: https://www.bitsoftware.eu/cariere-la-bitsoftware-solutii-software-de-business-erp-crm-bi-wms/#
2. Open “peviitor.ro page”, click “Firme”, search for “BIT Software” and click on “BIT Software”.
3. Check the jobs displayed on “BIT Software” website and the job displayed on page “peviitor.ro” for the “BIT Software” company.

Actual results
1. On “BIT Software” website section career, are displayed in total 5 jobs: “Channel Manager”, “Consultant Implementare”, “Consultant Senior – Suport Tehnic”, “Product Manager”, “Account Manager”.
2. On “peviitor.ro” for “BIT Software” company it is mentioned one job “Account Manager”.

Expected results
1. On “peviitor.ro” should be displayed in total 5 jobs for company “Bit Software”.

![BIT Software website](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/aee40670-9ecc-4208-a9f1-98db69573489)
![peviitor ro website](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/fe6c53a9-7301-47a1-b7e0-f874dcecef86)

**Comment by RaresCode** [comment]
Fixed can you retest??
