### ISSUE TITLE
Logo is not displayed correctly on site peviitor.ro, company "iuliuscompany".

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#43]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

- Steps to reproduce

1.Open peviitor URL
2.Put the name "iuliuscompany" in the search field
3.Press the button "Caută"
4.You will see that the logo appeared incomplete.
5. Open the career page: https://cariere.iuliuscompany.ro/
6. You will see that the logo is differently.

- Expected results

Logo to appear on the "peviitor.ro" site correctly.

- Actual results

Logo appear incomplete on the "peviitor.ro" site

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/1cbcf619-8fcb-4055-bf04-93713680911c)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by IvanSorina** [comment]
Retest.
