### ISSUE TITLE
On peviitor.ro, the Carturesti position "Responsabil tehnic regional/national" is missing

### ISSUE THREAD

**Issue by MarinaCosmina** [peviitor-ro/JobsScrapers#44]
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

Steps to reproduce:
1.	Open “Carturesti” career page: https://carturesti.ro/info/joburi
2. 	Check the jobs displayed on “Carturesti” website.
3.	Open “peviitor.ro page”.
4.	Click “Firme”.
5.	Search for “Carturesti”. 
6.	Click on “Carturesti”.
7.     Check the jobs displayed on page “peviitor.ro” for "Carturesti".

Actual results:
1.	On “Carturesti” website section career, are displayed in total 5 jobs: “Librar”, “Operator depozit (manipulant, picker)”, “Manager librărie”, “Coordonator echipă administrare personal și salarizare”, “Responsabil tehnic regional/național”.
2.	On “peviitor.ro” website for “Carturesti” are displayed 4 jobs “Librar”, “Operator depozit (manipulant, picker)”, “Manager librărie”, “Coordonator echipă administrare personal și salarizare”.

Expected results:
1.	On the website “peviitor.ro” should be displayed 5 jobs for “Carturesti”.
![peviitorJobsCarturesti](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/b2ab13cc-0701-4ee9-ac81-3c586e77af14)
![CarturestiJobs](https://github.com/peviitor-ro/JobsScrapers/assets/100074910/36e0d905-23b7-4b24-bd1b-b78245ba6627)

**Comment by RaresCode** [comment]
Fixed can you retest? and close if everything is fine?
