### ISSUE TITLE
Missing job "Business Operations Support Responsible -Dragomirești Deal, Ilfov" from site peviitor.ro

### ISSUE THREAD

**Issue by FloBut** [peviitor-ro/JobsScrapers#5]
Enviroment

URL: https://peviitor.ro/
browser: Chrome
device: Computer
OS: windows

Steps to reproduce

1. Open the company careers page: https://www.titanmachinery.ro/en/pag/careers?page=
2. Pay attention to no of jobs displayed
3. Open peviitor URL
4. Put the name "Titanmachinery" in the search field
5. Press the button "cauta"
6. Scroll until the end of displayed jobs
7. Pay attention that job "Business Operations Support Responsible -Dragomirești Deal, Ilfov" is not displayed

Expected results

"Business Operations Support Responsible -Dragomirești Deal, Ilfov " to be displayed on peviitor.ro after searching all the jobs from "Titanmachinery" 

Actual results

There are no job with titles "Business Operations Support Responsible -Dragomirești Deal, Ilfov" displayed on peviitor.ro after applying filter for searching the company "Titanmachinery"

**Comment by RaresCode** [comment]
Fixed
