### ISSUE TITLE
Missing job from site peviitor.ro, company "affidearomania"

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#52]
URL: https://peviitor.ro/
browser: Chrome
device: Computer
OS: windows

- Steps to reproduce

1. Open the company recruitee page: https://affidearomania.recruitee.com/
2. Pay attention that are showed twelve jobs
3. Open peviitor URL
4. Put the name "affidearomania" in the search field
5. Press the enter button
6. Pay attention that is displayed eleven jobs.

- Expected results

It should displayed the job "Asistent medical radiologie si imagistica - Bucuresti, Cluj" at "peviitor.ro" site, company "affidearomania".

- Actual results

It isn't displayed the job "Asistent medical radiologie si imagistica - Bucuresti, Cluj" at "peviitor.ro" site, company "affidearomania".

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/491aa5a5-e79f-4de7-b88e-04fc5cdb13be)

**Comment by RaresCode** [comment]
It seems the job it's there can you retest and close this bug if everything is fine?

**Comment by IvanSorina** [comment]
Retest
