### ISSUE TITLE
InterbrandsOrbico: The number of jobs displayed on Peviitor (0) and the ones displayed on the company website (68) aren't the same. 

### ISSUE THREAD

**Issue by cristiol** [peviitor-ro/JobsScrapers#55]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows

STEPS TO REPRODUCE:

Open https://scrapers.peviitor.ro/.
Type "InterbrandsOrbico" in the search bar.
Click on InterbrandsOrbico folder
Check the number of jobs available for "InterbrandsOrbico".
Open "https://interbrandsorbico.recruitee.com/".
Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs displayed on "https://peviitor.ro/" and the number of jobs displayed on the company website should be the same.

ACTUAL RESULT:
There are 0 jobs displayed on Peviitor website, while on the company website there are displayed 68 available jobs.

![ineterbrand_scrapers](https://github.com/peviitor-ro/JobsScrapers/assets/142798921/9b5c20e0-91b9-4786-9d9e-89de2a63c66b)

![ineterbrand_site](https://github.com/peviitor-ro/JobsScrapers/assets/142798921/df303d73-36b2-4989-8166-c04d5e4d4bbb)

**Comment by RaresCode** [comment]
Fixed, can you retest and close the bug?
