### ISSUE TITLE
In the search box of the site peviitor.ro, company "Bakertilly" appears twice. 

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#57]
URL: https://peviitor.ro/
browser: Chrome
device: Computer
OS: windows

> Steps to reproduce

1. Open peviitor.ro
2. Put the name "Bakertilly"  in the search field

> Expected result

"Bakertilly" should appear once on "peviitor.ro" site.

> Actual result

 "Bakertilly" appear twice on "peviitor.ro" site.

![image](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/fd3a7d7f-4376-41a9-a67a-15cb1eec2c8a)

**Comment by RaresCode** [comment]
Please add this issue in https://github.com/peviitor-ro/firme-peviitor/issues and assign it to Laurentiu!
