### ISSUE TITLE
Missing links from all jobs for "basware" company on site peviitor.ro

### ISSUE THREAD

**Issue by FloBut** [peviitor-ro/JobsScrapers#6]
**Enviroment**

url: https://peviitor.ro/
browser: Chrome
device: Computer
OS: windows

Steps to reproduce

1. Open the company careers page: https://careers.basware.com/
2. Pay attention to no of jobs displayed
3. Open peviitor - url
4. Put the name "basware" in the search field
5. Press the button "cauta"
6. Scroll until the end of displayed jobs
7. Click on button "Vezi postul" for each job displayed
 
 **Expected results**

Job to be displayed on "peviitor.ro" after press the button "Vezi postul"  from site  "https://careers.basware.com/"

Actual results

The link from button "Vezi postul" on site  "https://peviitor.ro/" displayed "404 not found".

**Comment by RaresCode** [comment]
Fixed
