### ISSUE TITLE
Splendor -  The message " Multiple city names from Romania  is not a city in Romania" is displayed instead of the job locations

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#63]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " Splendor " Company
3. Check the job locations
4. Open https://www.splendor.ro/cariera.html#2
5. Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:
 The message " Multiple city names from Romania  is not a city in Romania" is displayed instead of the job locations

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/f542f5a2-1dfc-4b37-a6d9-1cc03ffcfec7)

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/934232aa-9a99-4d5e-a6d0-26eb7a1d9df9)

https://peviitor.ro/rezultate?q=splendor&country=Rom%C3%A2nia&page=1

**Comment by RaresCode** [comment]
fixed can you retest?

**Comment by Geo843** [comment]
Retested, all good.
