### ISSUE TITLE
Velpitar - The message " Bucuresti, Brasov, Chitila, Giurgiu, Iasi, Oradea, Pitesti  is not a city in Romania" is not recognized on the job locations

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#65]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " Velpitar" Company
3. Check the job locations
4. Open https://peviitor.ro/rezultate?q=velpitar&country=Rom%C3%A2nia&page=3
5. Check the job locations

EXPECTED RESULTS:

1. Job locations are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:

1. The message " Bucuresti, Brasov, Chitila, Giurgiu, Iasi, Oradea, Pitesti is not a city in Romania"  is not recognized on the job locations.
2. There are 28 jobs : 
                                Bucuresti :  7
                                Brasov:       4
                                Chitila :      3
                                Giurgiu :     2
                                 Iasi :           9
                                 Oradea :    1
                                 Pitesti :      2

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/d192206c-9524-42bd-9a1b-3650d9546a26)
![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/772f4e73-ab0d-40a4-953b-c425f0ef6d3a)
![screencapture-velpitar-ro-cariere-vel-pitar-2023-11-27-11_57_13](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/8669afc1-d910-479a-9944-cf1bfe3d3d44)

https://peviitor.ro/rezultate?q=velpitar&country=Rom%C3%A2nia&page=1

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Geo843** [comment]
Retested,  Job locations are the same in Scrapers-UI as on the company website.
