### ISSUE TITLE
Typingdna -  The " Careers " button  is not functional.

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#68]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser.
2. Search for "Typingdna  " Company.
3. Check the " Careers " button.

EXPECTED RESULTS:
1. The " Careers " button exists and is functional

ACTUAL RESULTS:
1. The " Careers " button  is not functional.

https://github.com/peviitor-ro/JobsScrapers/assets/71781611/fac15a1c-2e33-493f-b009-db0bd820fa22

**Comment by RaresCode** [comment]
They do not have a careers page anymore, close the bug
