### ISSUE TITLE
Oradeatechhub - The message "Romania, Oradea/Remote, Cluj is not a city in Romania" is displayed instead of the job locations 

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#78]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " Oradeatechhub " Company
3. Check the job locations
4. Open https://www.oradeatechhub.ro/jobs
5. Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website.

ACTUAL RESULTS:
The message "Romania, Oradea/Remote, Cluj is not a city in Romania" is displayed instead of the job locations 

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/69f493e2-126c-44e7-b381-17ebd4b8d2bb)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Geo843** [comment]
After retesting,  Job locations are the same in Scrapers-UI as on the company website.
