### ISSUE TITLE
Nielseniq -  Number of jobs on the  "Careers " button page is not the same with the "See Jobs" button page.

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#81]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Nielseniq" Company
3. Click on the "Careers" button.
4. Open the "Careers" button.
5. Click on the "See Jobs".
6. Open https://nielseniq.com/?s=&market=global&language=en&orderby=&order=&post_type=career_job&job_locations=romania&job_teams=&job_types=

EXPECTED RESULTS:
1. Number of jobs on  the "Careers " button page is  the same with the "See Jobs" button page.

ACTUAL RESULTS:
1.  Number of jobs on "Careers " button page is not the same with the  "See Jobs" button page.

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/ba3803ac-a165-4545-80ae-ac47fce77048)

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/ba9d34f7-d04e-4a00-9f9b-1e31bf1aa6f0)
![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/458f484f-b78c-4c88-8da3-85a14ae4e754)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Geo843** [comment]
Re-tested, Number of jobs on the "Careers " button page is the same with the "See Jobs" button page.
