### ISSUE TITLE
Nagarro - The message "Romania is not a city in Romania" is displayed instead of the job locations 

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#82]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Nagarro " Company
3. Check the job locations
4. Open https://www.nagarro.com/en/careers/job-search?country=romania&city=wfa/remote
5. Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website

ACTUAL RESULTS:
The message "Romania is not a city in Romania" is displayed instead of the job locations

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/1217b4b4-08b1-4fa2-bae8-56fe001e5bc7)

https://www.nagarro.com/en/careers/job-search?country=romania&city=wfa/remote

**Comment by RaresCode** [comment]
Can you retest?

**Comment by Geo843** [comment]
Re-tested, Job locations are the same in Scrapers-UI as on the company website
