### ISSUE TITLE
Leier - The message " Iași, suceava, botosani, Vaslui, Neamt, Bacau, Vrancea, Galati " is not a city in Romania.

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#83]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " Leier  " Company.
3. Click " Careers" button.
4. Open https://www.leier.ro/cariere/
5. Check the job locations.

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website.

ACTUAL RESULTS:
The message " Iași, suceava, botosani, Vaslui, Neamt, Bacau, Vrancea, Galati " is not a city in Romania.

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/4790d834-dff7-450f-9be5-632cb6b84038)

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/b6efdf6f-24ea-42b8-a806-fda6e9944551)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Geo843** [comment]
Re-tested, Job locations are the same in Scrapers-UI as on the company website.
