### ISSUE TITLE
InterbrandsOrbico -  The message " Targu Mures is not a city in Romania" is displayed instead of the job locations.

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#85]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " InterbrandsOrbico "is  Company
3. Open https://interbrandsorbico.recruitee.com/
4. Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website.

ACTUAL RESULTS:
The message " Targu Mures is not a city in Romania" is displayed instead of the job locations.

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/02324f52-dfc6-4891-be78-0629348e74ec)

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/23dfae40-fbd9-437e-91c9-5f78fc36fcc5)

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/07b1ffa0-e54d-4c5c-9536-0b930a10cacb)

**Comment by RaresCode** [comment]
Can you retest?

**Comment by Geo843** [comment]
Re-tested, Job locations are the same in Scrapers-UI as on the company website.
