### ISSUE TITLE
Inova - Missing " Targetare .ro" button ; -  Graph without active data for the jobs on

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#89]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Inova" Company
3. Click on the "Targetare.ro" button
4. Open page "Targetare.ro"
5. Check the graph functionality.

EXPECTED RESULTS:

1. The "Targetare.ro" button is functional and the page is opend.
2. The graph have activ data and show the number of valid jobs

ACTUAL RESULTS:
1. Missing "Targetare.ro" button
2. Graph without active data for the jobs on.

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/71781611/77c70206-839f-4cb3-bf79-7293619a9f1b)

**Comment by lalalaurentiu** [comment]
the file name must be the same as company name 
<img width="1440" alt="Screenshot 2023-12-06 at 17 57 34" src="https://github.com/peviitor-ro/JobsScrapers/assets/67306273/b707b6ac-9231-4c49-ac92-70e1bf17c03d">

**Comment by RaresCode** [comment]
fixed can you retest

**Comment by lalalaurentiu** [comment]
working
