### ISSUE TITLE
Missing job "Merchandiser- Philip Morris - Resita" from site peviitor.ro

### ISSUE THREAD

**Issue by IvanSorina** [peviitor-ro/JobsScrapers#9]
URL: https://peviitor.ro/
browser: Microsoft Edge
device: Computer
OS: windows

Steps to reproduce

Open the company recruitee page: https://interbrandsorbico.recruitee.com/
Pay attention to no of jobs displayed
Open peviitor URL
Put the name "InterbrandsOrbico" in the search field
Press the button "Caută"
Scroll until the end of displayed jobs
Pay attention that job "Merchandiser- Philip Morris - Resita" is not displayed

Expected results

"Merchandiser- Philip Morris - Resita" to be displayed on peviitor.ro after searching all the jobs from "InterbrandsOrbico"

Actual results

There are no job with titles "Merchandiser- Philip Morris - Resita" displayed on peviitor.ro after applying filter for searching the company "InterbrandsOrbico"
![Screenshot 2023-08-11 124808](https://github.com/peviitor-ro/JobsScrapers/assets/134533131/33c6f075-f457-4205-971f-5d01120e6d27)

**Comment by RaresCode** [comment]
Not a bug!
