### ISSUE TITLE
InterbrandsOrbico  - Status Inactive

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#90]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " InterbrandsOrbico " Company.
3. Click on the "Run scraper"

EXPECTED RESULTS:
" Run scraper" is working and Status is " Active"

ACTUAL RESULTS:
Status Inactive

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/3a37a5db-eb02-4f5f-977a-517bf9f9b128)

**Comment by RaresCode** [comment]
Can you retest?

**Comment by Geo843** [comment]
Re-tested, " Run scraper" is working and Status is " Active"
