### ISSUE TITLE
Ensemblesoftware -   Error Status "Database"  button instead of "Active"

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#92]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " Ensemblesoftware " Company.
3. Verify  "Status"button.

EXPECTED RESULTS:
Status button is "Active".

ACTUAL RESULTS:
Error Status "Database"  button instead of "Active"

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/714709ae-2a45-4a54-9079-1ba0518f5e43)

**Comment by RaresCode** [comment]
can you retest and confirm if the bug is still there? I cannot see it on my end.
![image](https://github.com/peviitor-ro/JobsScrapers/assets/91252395/12f54d93-eed2-4a43-a278-3757b26704a6)

**Comment by Geo843** [comment]
Re-tested, Status button is "Active".
