### ISSUE TITLE
Covalact - The message " Romania is not a city in Romania" is displayed instead of the job locations.

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#94]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Covalact  " Company.
3. Check the "Careers" button.
4. Check the "See Jobs" button.
5. Check the job locations.

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website.

ACTUAL RESULTS:
The message " Romania is not a city in Romania" is displayed instead of the job locations.

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/64f007ec-8745-413b-867a-3da8b0988d97)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Geo843** [comment]
Re-tested, Job locations are the same in Scrapers-UI as on the company website.
