### ISSUE TITLE
Conexdist - The message " Bucuresti, Oradea, Voluntari, Cluj, Pitesti, Buzau , Craiova,Constanta is not a city in Romania" is displayed instead of the job locations. 

### ISSUE THREAD

**Issue by Geo843** [peviitor-ro/JobsScrapers#95]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for " Conexdist  " Company
3.Check "Careers" button.
4. Check "See jobs " button.
5. Check the job locations

EXPECTED RESULTS:
Job locations are the same in Scrapers-UI as on the company website.

ACTUAL RESULTS:
The message " Bucuresti, Oradea, Voluntari, Cluj, Pitesti, Buzau , Craiova,Constanta is not a city in Romania" is displayed instead of the job locations. 

![image](https://github.com/peviitor-ro/JobsScrapers/assets/71781611/23a83804-fb0a-446a-8ed4-1b806020010e)

**Comment by RaresCode** [comment]
Fixed can you retest?

**Comment by Geo843** [comment]
Re-tested, Job locations are the same in Scrapers-UI as on the company website
