### ISSUE TITLE
Reinert

### ISSUE THREAD

**Issue by lalalaurentiu** [peviitor-ro/JobsScrapers#97]
# Issue Description:
The Python file responsible for job retrieval returns an empty list upon completion of the scraper execution. The expected behavior is to obtain a list containing job details.

## Details:
The current behavior of the Python script that retrieves jobs results in an empty list upon completion of the scraping process. The anticipated outcome should be a populated list containing job details retrieved.
<img width="1440" alt="Screenshot 2023-12-08 at 18 48 33" src="https://github.com/peviitor-ro/JobsScrapers/assets/67306273/86b050a2-793d-47df-adc9-c2af7ff0c21b">

## Additional Context:
Please review the Python file logic for job retrieval to ensure accurate list generation post-execution.

## Expected Outcome:
Upon the execution of the Python script, it should return a list populated with job details. Note that the company has job openings available on their careers website.

**Comment by RaresCode** [comment]
The scraper is disabled as the jobs lead to 404 page currently 
![image](https://github.com/peviitor-ro/JobsScrapers/assets/91252395/b0ba1acc-dd59-4ac1-a6b6-999e1e494049)
